FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ARG HEREYOUGOBOT_PORT
ARG CHAT_ID
ENV HEREYOUGOBOT_PORT=${HEREYOUGOBOT_PORT}
ENV CHAT_ID=${CHAT_ID}

WORKDIR /app
COPY app/server.py /app/server.py

EXPOSE ${HEREYOUGOBOT_PORT}
CMD ["python", "/app/server.py"]
